### ISSUE TITLE
Adding a filter to a code-workspace triggers continous changes to settings.json

### ISSUE THREAD

**Issue by jschmer** [mbehr1/dlt-logs#13]
If you add a filter to the currently loaded code-workspace, the extension seems to regenerate new filter ids in settings.json forever. VS code UI will show this as a flickering icon for unsaved changes.

example.code-workspace
```
{
	"folders": [
		{
			"path": "."
		}
	],
	"settings": {
		"dlt-logs.filters":[
			{
				"name": "F1",
				"type": 3,
				"apid": "TEST",
				"ctid": "ME",
				"payloadRegex": "^Hello (?<STATE_world>.*)"
			},
		]
	}
}
```
Once you take that filter out, it will stop. I think dlt-log extension v1.1.x was working without this issue.

I'm running on Windows with VS code v1.52.1 and dlt-log extension v1.8.0

**Comment by mbehr1** [comment]
well, what the extension does is that it adds the missing "id" (uuid for each filter). So yes, it does change settings. But I would not understand why this happens endlessly. The sequence should be:
1. you change manually settings json. Once done you save.
2. extension is notified about changed settings. parses them again, sees the missing id, adds it and updates settings.
3. this leads to a changed settings json (but with the new attribute id added).

And yes, this is new since some versions where I added the "listen to conf changes to avoid the need to close and reopen the doc first".

Do you have a different sequence?
Can you paste the logs? (from developer tools -> console).

**Comment by jschmer** [comment]
Giving a bit more context here:
- Open VS Code
- File -> Open Workspace -> "E:\TEMP\vs-code-dlt-log\example.code-workspace"
  - Content as described above, e.g. including a "dlt-logs.filters" config in the workspace file itself
- Open any DLT file
- Notice that the filter uuid in %APPDATA%\Roaming\Code\User\settings.json is updated continously

Log available at https://gist.github.com/jschmer/ae455fe0bbf695bd1ba72e39b9061fbc

**Comment by jschmer** [comment]
Just noticed it actually replaces & adapts the config in %APPDATA%\Roaming\Code\User\settings.json with the config from the code-workspace file but keeps seeing the config from the code-workspace without the uuid.

**Comment by mbehr1** [comment]
I think I found a problematic use-case I don't consider yet:
if you have two different windows with dlt-files open, those will run in sep. processes. So they both react at the same time to the config change. Will investigate into that use-case.

**Comment by mbehr1** [comment]
ah. @jschmer and you're use-case is even another one. You're changing a workspace config... ok. Will check that as well. Thx for the issue report.

**Comment by mbehr1** [comment]
There was even a "todo" already in current code. Implemented this now. @jschmer  can you try the new release?

**Comment by jschmer** [comment]
Yes, that fixed my use case, thanks!
